// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using USWildfireProject.Data;

#nullable disable

namespace USWildfireProject.Migrations
{
    [DbContext(typeof(WildfireContext))]
    [Migration("20231020155923_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.12");

            modelBuilder.Entity("USWildfireProject.Models.Wildfire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CauseAgeCategory")
                        .HasColumnType("TEXT");

                    b.Property<string>("CauseClassification")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("ContainmentDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ContainmentDayOfYear")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly?>("ContainmentTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("County")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DiscoverDate")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly?>("DiscoverTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("DiscoveryDayOfYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GeneralCause")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("TEXT");

                    b.Property<double>("Size")
                        .HasColumnType("REAL");

                    b.Property<char>("SizeClass")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Wildfires");
                });
#pragma warning restore 612, 618
        }
    }
}
